DATA = common.c

CWEBINPUTS = $(CWEB_SRC_DIR)

CWEBEES = common.c

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal -I$(PROJECTDIR)/lib1/web

all: $(DATA) 

$(CWEBEES): $(CWEB_SRC_DIR)/common.w $(CWEB_SRC_DIR)/common.h kertex.ch
