PROG = pltotf

LIBES = $(WEBLIB) $(PASCALLIB)

MAKE_STATIC=YES

COBJ =	pltotf.o

all: $(PROG)

pltotf.p pltotf.pool:	$(KNUTH_SRC_DIR)/texware/pltotf.web pltotf.ch
	$(M_DIR)/tangle $(KNUTH_SRC_DIR)/texware/pltotf.web pltotf.ch

pltotf.c coerce.h: 	pltotf.p pltotf.h
	cat $(PROJECTDIR)/lib1/pascal/ppdef.data\
		$(PROJECTDIR)/lib1/web/ppdef.data\
		pltotf.p \
		| $(M_DIR)/pp2rc -h pltotf.h\
		| $(M_DIR)/fixwrites >pltotf.c
	
