PROG = bibtex

LIBES = $(WEBLIB) $(PASCALLIB)

MAKE_STATIC=YES

COBJ =	bibtex.o extra.o

all: $(PROG)

bibtex.p bibtex.pool:	$(BIBTEX_SRC_DIR)/bibtex.web webmerged$(BIGTEX).ch
	$(M_DIR)/tangle $(BIBTEX_SRC_DIR)/bibtex.web webmerged$(BIGTEX).ch

bibtex.c coerce.h: 	bibtex.p bibtex.h
	cat $(PROJECTDIR)/lib1/pascal/ppdef.data\
		$(PROJECTDIR)/lib1/web/ppdef.data\
		./ppdef.data bibtex.p\
		| $(M_DIR)/pp2rc -h bibtex.h\
		| $(M_DIR)/fixwrites >bibtex.c

