PROG = cweave

MAKE_STATIC=YES

CWEBEES = cweave.c

CFILES = cweave.c $(OBJDIR)/cweb/bin1/common.c

COBJ = cweave.o common.o

CWEBINPUTS = $(PROJECTDIR)/cweb/bin1

LIBES = $(WEBLIB)

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): cweave.w  kertex.ch

