PROG = cweave

MAKE_STATIC=YES

CWEBEES = cweave.c

CFILES = cweave.c $(OBJDIR)/cweb/bin1/common.c

COBJ = cweave.o common.o

CWEBINPUTS = $(KNUTH_SRC_DIR)/cweb

LIBES = $(WEBLIB)

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): $(KNUTH_SRC_DIR)/cweb/cweave.w  kertex.ch

