PROG = cwmerge

MAKE_STATIC=YES

COBJ = wmerge.o

LIBES = $(WEBLIB)

CWEBINPUTS = $(KNUTH_SRC_DIR)/cweb

CWEBEES = wmerge.c

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): $(KNUTH_SRC_DIR)/cweb/examples/wmerge.w kertex.ch

