PROG = ctangle

MAKE_STATIC=YES

CWEBEES = ctangle.c

CFILES = ctangle.c $(OBJDIR)/cweb/bin1/common.c

COBJ = ctangle.o common.o

CWEBINPUTS = $(KNUTH_SRC_DIR)/cweb

LIBES = $(WEBLIB)

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): $(KNUTH_SRC_DIR)/cweb/ctangle.w  kertex.ch

