PROG = ctangle

MAKE_STATIC=YES

CWEBEES = ctangle.c

CFILES = ctangle.c $(OBJDIR)/cweb/bin1/common.c

COBJ = ctangle.o common.o

CWEBINPUTS = $(PROJECTDIR)/cweb/bin1

LIBES = $(WEBLIB)

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): ctangle.w kertex.ch

