PROG = ctangle

MAKE_STATIC=YES

CWEBEES = ctangle.c

CFILES = ctangle.c $(OBJDIR)/cweb/bin1/common.c

COBJ = ctangle.o common.o

CWEBINPUTS = $(CWEB_SRC_DIR)

LIBES = $(WEBLIB)

XCPPFLAGS = -I$(PROJECTDIR)/lib1/pascal

all: $(PROG) 

$(CWEBEES): $(CWEB_SRC_DIR)/ctangle.w  $(CWEB_SRC_DIR)/common.h \
	kertex.ch

