PROG = pooltype

LIBES = $(WEBLIB) $(PASCALLIB)

MAKE_STATIC=YES

COBJ =	pooltype.o

all: $(PROG)

pooltype.p pooltype.pool:	$(KNUTH_SRC_DIR)/texware/pooltype.web pooltype.ch
	$(M_DIR)/tangle $(KNUTH_SRC_DIR)/texware/pooltype.web pooltype.ch

pooltype.c coerce.h: 	pooltype.p pooltype.h
	cat $(PROJECTDIR)/lib1/pascal/ppdef.data\
		$(PROJECTDIR)/lib1/web/ppdef.data\
		pooltype.p \
		| $(M_DIR)/pp2rc -h pooltype.h\
		| $(M_DIR)/fixwrites >pooltype.c
	
